
spring:
  application:
    name: SpringSecurityJWT
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwtproject
    username: yongjin
    password: 8962
    jpa:
      database : mariadb
      database-platform: org.hibernate.dialect.MariaDBDialect
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  jwt:
    secret : sfsxfaslfjqkdpdsvcizxkkasdefcvvsdfasdacaefcsc